<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_58482513c2d94',
	'title' => 'Advokater',
	'fields' => array (
		array (
			'key' => 'field_584826f379385',
			'label' => 'Bild',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5857d33f20654',
			'label' => 'Citat',
			'name' => 'quote',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_58483ba0a0d97',
			'label' => 'E-post',
			'name' => 'email',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_58483bb0a0d98',
			'label' => 'Telefonnummer',
			'name' => 'phone_number',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_5857d3ff20658',
			'label' => 'Skype',
			'name' => 'skype',
			'type' => 'url',
			'instructions' => 'Länk till skypekonto',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_585b218949f77',
			'label' => 'Sociala medier',
			'name' => 'social_media',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Lägg till social media',
			'sub_fields' => array (
				array (
					'key' => 'field_585b219849f78',
					'label' => 'Social media',
					'name' => 'social_item',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'facebook' => 'Facebook',
						'twitter' => 'Twitter',
						'linkedin' => 'LinkedIn',
						'google-plus' => 'Google+',
						'pinterest' => 'Pinterest',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_585b21f849f79',
					'label' => 'Länk',
					'name' => 'link',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'lawyer',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_586903b95c413',
	'title' => 'Användare',
	'fields' => array (
		array (
			'key' => 'field_586903c9e6966',
			'label' => 'Profilbild',
			'name' => 'profile_picture',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_586903f4e6967',
			'label' => 'Sociala medier',
			'name' => 'profile_social_media',
			'type' => 'repeater',
			'instructions' => 'Lägg till dina sociala medier',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Lägg till rad',
			'sub_fields' => array (
				array (
					'key' => 'field_5869040ce6968',
					'label' => 'Ikon',
					'name' => 'profile_icon',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'facebook' => 'Facebook',
						'instagram' => 'Instagram',
						'linkedin' => 'LinkedIn',
						'google-plus' => 'Google+',
						'twitter' => 'Twitter',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_58690456e6969',
					'label' => 'Länk',
					'name' => 'profile_link',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'user_role',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_584691466a43e',
	'title' => 'General',
	'fields' => array (
		array (
			'key' => 'field_584696439ed25',
			'label' => 'Header',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_58469168b3379',
			'label' => 'Logga',
			'name' => 'logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5869153e905bb',
			'label' => 'Öppettider',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_58691559905bc',
			'label' => 'Måndag',
			'name' => 'Monday',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5869158d905bd',
			'label' => 'Tisdag',
			'name' => 'Tuesday',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_58691596905be',
			'label' => 'Onsdag',
			'name' => 'Wednesday',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_586915a0905bf',
			'label' => 'Torsdag',
			'name' => 'Thursday',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_586915aa905c0',
			'label' => 'Fredag',
			'name' => 'Friday',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_586915b1905c1',
			'label' => 'Lördag',
			'name' => 'Saturday',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_586915c1905c2',
			'label' => 'Söndag',
			'name' => 'Sunday',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5846914eb3377',
			'label' => 'Rådgivning',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_58696072bb397',
			'label' => 'Bakgrundsfärg',
			'name' => 'background_color_question',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'white' => 'Vit',
				'grey' => 'Grå',
				'ghost' => 'Blå',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_586dfec7f0df5',
			'label' => 'Inloggad för att skicka fråga?',
			'name' => 'logged_in',
			'type' => 'true_false',
			'instructions' => 'Ska man vara inloggad för att kunna skicka en fråga? 
Alternativet är att vem som helst kan skicka in en fråga.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5846915eb3378',
			'label' => 'Footer',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5853a08ca7d72',
			'label' => 'Social media',
			'name' => 'social_footer',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Lägg till social media',
			'sub_fields' => array (
				array (
					'key' => 'field_5853a0a7a7d73',
					'label' => 'Ikon',
					'name' => 'icon',
					'type' => 'select',
					'instructions' => 'Välj vilken ikon som ska visas',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'facebook' => 'Facebook',
						'instagram' => 'Instagram',
						'linkedin' => 'LinkedIn',
						'twitter' => 'Twitter',
						'google-plus' => 'Google+',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_5853a165a7d74',
					'label' => 'Länk',
					'name' => 'link',
					'type' => 'url',
					'instructions' => 'Vart ska ikonen länka?',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
		array (
			'key' => 'field_5853a23856747',
			'label' => 'Copyright',
			'name' => 'copyright',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-alternativ',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_586e057e506b6',
	'title' => 'Kontakt',
	'fields' => array (
		array (
			'key' => 'field_586e090f3b3d6',
			'label' => 'Telefonnummer',
			'name' => 'contact_phone_number',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_586e09353b3d7',
			'label' => 'Adress',
			'name' => 'contact_adress',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_586e09eb3b3d8',
			'label' => 'Epost',
			'name' => 'contact_email',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_586f8510f606e',
			'label' => 'Google maps',
			'name' => 'google_maps',
			'type' => 'text',
			'instructions' => 'Kopiera iframe länken du får om du går in på maps.google.com',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5870d8dc5f9db',
			'label' => 'Sociala medier',
			'name' => 'contact_social',
			'type' => 'true_false',
			'instructions' => 'Visa sociala medier? Du lägger till dessa i alternativ- footer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'templates/contact.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5853b67324966',
	'title' => 'Rådgivning',
	'fields' => array (
		array (
			'key' => 'field_5853b6a8d182c',
			'label' => 'Fråga',
			'name' => 'question',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_5853b6e9d182d',
			'label' => 'Svar',
			'name' => 'answer',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'question',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'featured_image',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5848376bcd72a',
	'title' => 'Sektioner',
	'fields' => array (
		array (
			'key' => 'field_58483783f3c88',
			'label' => 'Sektioner',
			'name' => 'sections',
			'type' => 'flexible_content',
			'instructions' => 'Lägg till sektion',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Lägg till sektion',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '58483793be6e8',
					'name' => 'hero',
					'label' => 'Hero',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_584837c8f3c89',
							'label' => 'Bakgrunsbild',
							'name' => 'image',
							'type' => 'image',
							'instructions' => 'Välj vilken bakgrundsbild du vill ha',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_5848380af3c8a',
							'label' => 'Rubrik',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5870e7a47bba5',
							'label' => 'Textfärg',
							'name' => 'text_color',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'white' => 'Vit',
								'black' => 'Svart',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5869466d31440',
							'label' => 'Storlek',
							'name' => 'size',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'large' => 'Stor',
								'small' => 'Liten',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
					'min' => '0',
					'max' => '1',
				),
				array (
					'key' => '5853aacc7b590',
					'name' => 'testimonial',
					'label' => 'Testimonial',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5853aad47b591',
							'label' => 'Bakgrund',
							'name' => 'background',
							'type' => 'select',
							'instructions' => 'Ska bakgrunden vara en bakgrundsbild eller ska det vara en bakgrundsfärg?',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'image' => 'Bakgrundsbild',
								'color' => 'Bakgrundsfärg',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5853ab297b592',
							'label' => 'Bakgrundsbild',
							'name' => 'background_image',
							'type' => 'image',
							'instructions' => 'Välj bakgrundsbild.',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5853aad47b591',
										'operator' => '==',
										'value' => 'image',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_5853abaa7b594',
							'label' => 'Filter',
							'name' => 'filter',
							'type' => 'select',
							'instructions' => 'Vilket filter ska det vara över bilden?',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5853aad47b591',
										'operator' => '==',
										'value' => 'image',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'none' => 'Inget',
								'light' => 'Ljusare',
								'dark' => 'Mörkare',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5853ab4f7b593',
							'label' => 'Bakgrundsfärg',
							'name' => 'background_color',
							'type' => 'select',
							'instructions' => 'Vilken färg?',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5853aad47b591',
										'operator' => '==',
										'value' => 'color',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'grey' => 'Ljusgrå',
								'black' => 'Svart',
								'orange' => 'Orange',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5853abf27b595',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'text',
							'instructions' => 'Max 30 tecken',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => 30,
						),
						array (
							'key' => 'field_5853acd47b597',
							'label' => 'Länk',
							'name' => 'link',
							'type' => 'page_link',
							'instructions' => 'Vart ska texten länka?',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'allow_archives' => 1,
							'multiple' => 0,
						),
						array (
							'key' => 'field_5853abf97b596',
							'label' => 'Ikon',
							'name' => 'icon',
							'type' => 'select',
							'instructions' => 'Vilken ikon ska vara med? (Om du inte väljer en så kommer texten att hamna centrerat).

OBS att ikonen inte kommer att synas i mobilt läge.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'map-marker' => 'Kartmarkerare',
								'calendar' => 'Kalender',
								'check' => 'Check',
								'laptop' => 'Laptop',
								'comments-o' => 'Pratbubblor',
								'commenting-o' => 'Pratbubbla',
								'address-card-o' => 'Visitkort',
							),
							'default_value' => array (
							),
							'allow_null' => 1,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '585421a841cc6',
					'name' => 'text-fields',
					'label' => 'Textfält',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_586ce4258fd5a',
							'label' => 'Antal fält',
							'name' => 'number',
							'type' => 'select',
							'instructions' => 'Ett eller två fält?',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'one' => 'Ett fält',
								'two' => 'Två fält',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_586ce4b48fd5d',
							'label' => 'Bakgrundsfärg',
							'name' => 'background_color',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'white' => 'Vit',
								'ghost' => 'Blå',
								'grey' => 'Grå',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_586ce4858fd5b',
							'label' => 'Rubrik',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_586ce4258fd5a',
										'operator' => '==',
										'value' => 'one',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_586ce4a68fd5c',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_586ce4258fd5a',
										'operator' => '==',
										'value' => 'one',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_586ce4f88fd5e',
							'label' => 'Knapptext',
							'name' => 'button_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_586ce50d8fd5f',
							'label' => 'Knapplänk',
							'name' => 'button_link',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'allow_archives' => 1,
							'multiple' => 0,
						),
						array (
							'key' => 'field_585421ce41cc7',
							'label' => 'Vänster fält',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_586ce4258fd5a',
										'operator' => '==',
										'value' => 'two',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'field_585421f741cca',
							'label' => 'Titel',
							'name' => 'title_left',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5854220a41ccb',
							'label' => 'Text',
							'name' => 'text_left',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_5854222241ccd',
							'label' => 'Ikon',
							'name' => 'icon_left',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'university' => 'Universitet',
								'line-chart' => 'Linjetabell',
								'balance-scale' => 'Balansvåg',
								'gavel' => 'Klubba',
								'trophy' => 'Trofé',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_585421e241cc8',
							'label' => 'Höger fält',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_586ce4258fd5a',
										'operator' => '==',
										'value' => 'two',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'field_585421eb41cc9',
							'label' => 'Titel',
							'name' => 'title_right',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5854221941ccc',
							'label' => 'Text',
							'name' => 'text_right',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_5854222c41cce',
							'label' => 'Ikon',
							'name' => 'icon_right',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'university' => 'Universitet',
								'line-chart' => 'Linjetabell',
								'balance-scale' => 'Balansvåg',
								'gavel' => 'Klubba',
								'trophy' => 'Trofé',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5863a4d47b376',
					'name' => 'slideshow',
					'label' => 'Bildspel',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5863a5647b378',
							'label' => 'Antal bilder',
							'name' => 'number',
							'type' => 'select',
							'instructions' => 'Hur många bilder ska visas på skärmen samtidigt?',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								1 => '1',
								2 => '2',
								3 => '3',
								4 => '4',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5863a5817b379',
							'label' => 'Slides',
							'name' => 'slides',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Lägg till slide',
							'sub_fields' => array (
								array (
									'key' => 'field_5863a5977b37a',
									'label' => 'Bild',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'url',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5863bd4d4e124',
					'name' => 'list_lawyers',
					'label' => 'Lista advokater',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_586545c4d46cb',
							'label' => 'Rubrik',
							'name' => 'title',
							'type' => 'text',
							'instructions' => 'Lägg till rubrik.
Alla advokater kommer att listas här nedan i egna boxar.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_58695fdf1722f',
							'label' => 'Bakgrundsfärg',
							'name' => 'background_color',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'white' => 'Vit',
								'grey' => 'Grå',
								'ghost' => 'Blå',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5866a5bd60e8c',
					'name' => 'hours',
					'label' => 'Öppettider',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5866a5c460e8d',
							'label' => 'Rubrik',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_58695ff717230',
							'label' => 'Bakgrundsfärg',
							'name' => 'background_color',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'white' => 'Vit',
								'grey' => 'Grå',
								'ghost' => 'Blå',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5866a6aa60e92',
							'label' => 'Vilken typ av öppettider ska det vara?',
							'name' => 'what_kind',
							'type' => 'select',
							'instructions' => 'Vanlig = de öppettider som du lagt in i \'alternativ\' kommer att visas. ||
Avvikande dagar =	Speciella öppettider som du lägger in själv. T.ex midsommarafton eller semesterstängt.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'weekday' => 'Vanlig',
								'special' => 'Avvikande dagar',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5866a71360e94',
							'label' => 'Speciella dagar',
							'name' => 'special_days',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5866a6aa60e92',
										'operator' => '==',
										'value' => 'special',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Lägg till rad',
							'sub_fields' => array (
								array (
									'key' => 'field_5866a811d37b7',
									'label' => 'Dag',
									'name' => 'special_day',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array (
									'key' => 'field_5866a81ad37b8',
									'label' => 'Tid',
									'name' => 'special_time',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '586ccfc93f95e',
					'name' => 'taxonomy',
					'label' => 'Rättsområden',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_586cd895150ef',
							'label' => 'Rubrik',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_586cd8a0150f0',
							'label' => 'Bakgrundsfärg',
							'name' => 'background_color',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'white' => 'Vit',
								'ghost' => 'Blå',
								'grey' => 'Grå',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_586ccff73f960',
							'label' => 'Rättsområde',
							'name' => 'list_fields',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Lägg till rad',
							'sub_fields' => array (
								array (
									'key' => 'field_586cd0033f961',
									'label' => 'Område',
									'name' => 'field',
									'type' => 'taxonomy',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'taxonomy' => 'lawyer_field',
									'field_type' => 'select',
									'allow_null' => 0,
									'add_term' => 1,
									'save_terms' => 0,
									'load_terms' => 0,
									'return_format' => 'object',
									'multiple' => 0,
								),
								array (
									'key' => 'field_586cd0233f962',
									'label' => 'Ikon',
									'name' => 'icon',
									'type' => 'text',
									'instructions' => 'Skriv in namnet på din ikon. Alla ikoner finns att hitta på http://fontawesome.io/icons/',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
						array (
							'key' => 'field_586ce93958c38',
							'label' => 'Knapptext',
							'name' => 'button_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_586ce94458c39',
							'label' => 'Knapplänk',
							'name' => 'button_link',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'allow_archives' => 1,
							'multiple' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page',
				'operator' => '!=',
				'value' => '8',
			),
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'templates/contact.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

endif;